// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eyzvvglpktfhgqrxfiph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5enZ2Z2xwa3RmaGdxcnhmaXBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0NDM4MTgsImV4cCI6MjA1ODAxOTgxOH0.XBA6w-wJ9Oi668joJCMhz7zbqSmW03GnjZvfPBSE0TM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);